// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMJ8Y3SQZdMk4RvGlV6glZmHzmoWdRVg',
    appId: '1:401030608943:web:d3c1f817c0ba0ef5adaeda',
    messagingSenderId: '401030608943',
    projectId: 'dungeonsanddragons-4cdfa',
    authDomain: 'dungeonsanddragons-4cdfa.firebaseapp.com',
    storageBucket: 'dungeonsanddragons-4cdfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU_HDQCjzejoOiFXwgJJsJkuwbzJ1o2Vw',
    appId: '1:401030608943:android:cc77102b8ccf38e1adaeda',
    messagingSenderId: '401030608943',
    projectId: 'dungeonsanddragons-4cdfa',
    storageBucket: 'dungeonsanddragons-4cdfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ63FicZJ-cuh3J62PHEGPrWb6xkCVL7Q',
    appId: '1:401030608943:ios:76541c6c560df734adaeda',
    messagingSenderId: '401030608943',
    projectId: 'dungeonsanddragons-4cdfa',
    storageBucket: 'dungeonsanddragons-4cdfa.appspot.com',
    iosBundleId: 'com.zui.dungeonsAndDragons',
  );
}
